#2)(b)
str=input("Enter the string:")
LowerCase=str.lower()
print("In Lower Case =",LowerCase)
UpperCase=str.upper()
print("In Upper Case =",UpperCase)
CapitilizeCase=str.capitalize()
print("In Capitilize Case =",CapitilizeCase)
TitleCase=str.title()
print("In Title Case =",TitleCase)
